### ISSUE TITLE
Attached UncaughtExceptionHandler still catches caught exceptions

### ISSUE THREAD

**Issue by AndyFrench** [MindscapeHQ/raygun4android#23]
Code:

```
try {
    return new Gson().fromJson(jsonStr, X.class);
}
catch (Exception ex) {
    return new X();
}
```

`new Gson().fromJson()` throws `JsonSyntaxException` which is still caught by app-wide 'UncaughtExceptionHandler' instantiated via `RaygunClient.AttachExceptionHandler()` - even though exception is being caught. 

Could this be due to being called from within an `IntentService` (so background)..?

**Comment by fundead** [comment]
Hi Andy,

Apologies in the delay in replying to this ticket, we missed this one. I have a point release scheduled for this provider and will attempt to repro this behavior during it. From research it may be due to the IntentService, perhaps some odd implementation detail with UncaughtExceptionHandler in this context. I will get back to you shortly on this.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.

**Comment by TheRealAgentK** [comment]
I've just tried to replicate this issues with the 4.0 provider and that doesn't seem to be a problem anymore.
