### ISSUE TITLE
Disk Space Environment Data overflows int reporting garbage negative numbers

### ISSUE THREAD

**Issue by DanFTRX** [MindscapeHQ/raygun4android#29]
https://github.com/MindscapeHQ/raygun4android/blob/master/src/main/java/com/mindscapehq/android/raygun4android/messages/RaygunEnvironmentMessage.java#L95   
The Disk space calculations use an integer when it should be using a long.

Integer.MaxValue() is approx 23^1 - 1
A GigaByte is 2^30
So anything over 2 Gigs overflows

See:
https://developer.android.com/reference/android/os/StatFs.html#getAvailableBlocksLong()
https://developer.android.com/reference/android/os/StatFs.html#getBlockSizeLong()

**Comment by fundead** [comment]
Hey,

Thanks for raising this, you're quite correct that it should be a long. The reason this wasn't added before now is due to legacy support as the minimum API level of the provider is 9 (Gingerbread) and this API was only made available in 18. Gingerbread is fairly long in the tooth at this point and while we aim to not make breaking changes where possible and support the maximum amount of devices, this seems like a worthwhile change to make as devices these days have a lot more storage space than legacy devices.

I will do some research into current version adoption and the impact that changing the minimum API version to 18 will have. If this is acceptable (which most likely it will) I'll make the change and do a release using the new long methods for the environment variables.

**Comment by DanFTRX** [comment]
If backwards compatibility is an issue, you might instead opt to simply cast the returned int's from the API calls to longs before multiplying them together,  as typically on android the returned values should not be large enough on their own to overflow int.

**Comment by DanFTRX** [comment]
Any word on this?

**Comment by fundead** [comment]
Unfortunately it looks like legacy platform usage is still relatively common for < API 18 (Jellybean) - we're looking at 3% according to  https://developer.android.com/about/dashboards/index.html. From a figure of 1.4 B devices active last year 42 million is a lot to exclude, and as this is an upstream vendor library providing backwards compatibility and the widest range of device support is a priority. The backwards compatibility is for the minimum API level; using `getAvailableBlocksLong()` requires raising this to API 18 which excludes those 42 M devices.

This is unfortunate as accurate disk space would be nice but blocking the provider from use is rather undesirable and directly conflicts with one of our design goals for the providers. A major version bump is a possibility however this excludes older devices from future features and fixes and introduces maintenance overhead which we strive to avoid. We'd like to keep an eye on this and will hopefully be able to upgrade the minimum version when sub-18 usage is below or around 1%.

In the meantime this provider is easily built with mvn so an alternative is to clone the repository, bump the API version in the POM, change the two lines of code and build it with `mvn install`.

Sorry we don't have a better story around this currently, ideally next year we'll see some version uptick and we can revisit it in the mainline release then.
